#!/bin/sh
./run -fv toplr -type black -k 4000 -att imp -demo false 
./run -fv toplr -type black -k 4000 -att exp -demo false 
./run -fv toplr -type black -k 4000 -att imp -demo true  
./run -fv toplr -type black -k 4000 -att exp -demo true  
./run -fv toplr -type gay -k 4000 -att imp -demo false 
./run -fv toplr -type gay -k 4000 -att exp -demo false 
./run -fv toplr -type gay -k 4000 -att imp -demo true  
./run -fv toplr -type gay -k 4000 -att exp -demo true  
./run -fv df -type black -k 4000 -att imp -demo false 
./run -fv df -type black -k 4000 -att exp -demo false 
./run -fv df -type black -k 4000 -att imp -demo true  
./run -fv df -type black -k 4000 -att exp -demo true  
./run -fv df -type gay -k 4000 -att imp -demo false 
./run -fv df -type gay -k 4000 -att exp -demo false 
./run -fv df -type gay -k 4000 -att imp -demo true  
./run -fv df -type gay -k 4000 -att exp -demo true  
