#!/bin/sh
./run -fv toplr -type black -att imp -demo false 
./run -fv toplr -type black -att exp -demo false 
./run -fv toplr -type black -att imp -demo true  
./run -fv toplr -type black -att exp -demo true  
./run -fv toplr -type gay -att imp -demo false 
./run -fv toplr -type gay -att exp -demo false 
./run -fv toplr -type gay -att imp -demo true  
./run -fv toplr -type gay -att exp -demo true  
./run -fv df -type black -att imp -demo false 
./run -fv df -type black -att exp -demo false 
./run -fv df -type black -att imp -demo true  
./run -fv df -type black -att exp -demo true  
./run -fv df -type gay -att imp -demo false 
./run -fv df -type gay -att exp -demo false 
./run -fv df -type gay -att imp -demo true  
./run -fv df -type gay -att exp -demo true  
